name = "yyplatform"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23liLA0oWDaqad8cb2"
GITHUB_OWNER = "onelyy"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://yyplatform.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://yyplatform.pages.dev/"

